"""Generate src/dsp/ToneSosTables.h from analysis/per_rate_sos.json.
Pole/zero pairing: conjugates together, leftover reals paired by proximity,
odd counts padded with origin zero/pole (magnitude-1, harmless). Sections
ordered by pole radius descending (largest first). Overall gain folded into
the first section's b coefficients. Usage: python3 gen_sos_tables.py"""
import json
import os
import sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(REPO, "analysis", "per_rate_sos.json")
DST = os.path.join(REPO, "src", "dsp", "ToneSosTables.h")
RATES = ["44100", "48000", "88200", "96000"]


def pair_up(roots):
    roots = [complex(r[0], r[1]) for r in roots]
    secs, used = [], [False] * len(roots)
    for i, r in enumerate(roots):
        if used[i]:
            continue
        if abs(r.imag) > 1e-9:
            best, bd = -1, 1e100
            for j in range(len(roots)):
                if j != i and not used[j]:
                    d = abs(roots[j] - np.conj(r))
                    if d < bd:
                        best, bd = j, d
            secs.append((r, roots[best]))
            used[i] = used[best] = True
        else:
            # pair with nearest real
            best, bd = -1, 1e100
            for j in range(len(roots)):
                if j != i and not used[j] and abs(roots[j].imag) <= 1e-9:
                    d = abs(roots[j].real - r.real)
                    if d < bd:
                        best, bd = j, d
            if best >= 0:
                secs.append((r, roots[best]))
                used[i] = used[best] = True
            else:
                secs.append((r, 0.0))
                used[i] = True
    return secs


def to_sos(entry):
    zp = pair_up(entry["zeros"])
    pp = pair_up(entry["poles"])
    n = max(len(zp), len(pp))
    while len(zp) < n:
        zp.append((0.0, 0.0))
    while len(pp) < n:
        pp.append((0.0, 0.0))
    order = sorted(range(n),
                   key=lambda i: -max(abs(pp[i][0]), abs(pp[i][1])))
    sos = []
    for i in order:
        (z1, z2), (p1, p2) = zp[i], pp[i]
        bb = np.poly([z1, z2]).real
        aa = np.poly([p1, p2]).real
        sos.append(([float(bb[0]), float(bb[1]), float(bb[2])],
                    [float(aa[0]), float(aa[1]), float(aa[2])],
                    float(max(abs(p1), abs(p2)))))
    return sos, entry["gain"]


def main():
    tables = json.load(open(SRC))
    out = []
    out.append("// GENERATED by analysis/circuit_trace/gen_sos_tables.py from")
    out.append("// analysis/per_rate_sos.json — do not hand-edit. Regenerate.")
    out.append("// Per-rate general-biquad tone tables (blue hardware truth).")
    out.append("// Sections per leg are pole-radius ordered, largest first;")
    out.append("// overall gain is folded into the first section's b coeffs.")
    out.append("#pragma once")
    out.append("")
    out.append("namespace ToneSos {")
    out.append("")
    out.append("constexpr int kNumRates = 4;")
    out.append("constexpr double kRates[kNumRates] = "
               "{44100.0, 48000.0, 88200.0, 96000.0};")
    out.append("constexpr int kMaxSections = 8;")
    out.append("")
    out.append("struct Section { float b0, b1, b2, a1, a2; };")
    out.append("")
    maxcheck = 0.0
    for t in range(1, 7):
        for r in RATES:
            e = tables[str(t)][r]
            sos, gain = to_sos(e)
            n = len(sos)
            maxcheck = max(maxcheck,
                           max(s[2] for s in sos) if sos else 0.0)
            import math as _m
            _gdb = 20.0 * _m.log10(abs(e["gain"]))
            out.append("// Tone %d @ %s Hz: %d sections, gain %+.4f dB" %
                       (t, r, n, _gdb))
            out.append("constexpr int kSections_%d_%s = %d;" % (t, r, n))
            out.append("constexpr Section kTone%d_%s[%d] = {" % (t, r, n))
            for i, (bb, aa, pr) in enumerate(sos):
                g = gain if i == 0 else 1.0
                out.append("    {%sf, %sf, %sf, %sf, %sf},  // prad %.4f" %
                           (repr(bb[0] * g), repr(bb[1] * g), repr(bb[2] * g),
                            repr(aa[1] / aa[0]), repr(aa[2] / aa[0]), pr))
            out.append("};")
            out.append("")
    out.append("} // namespace ToneSos")
    open(DST, "w").write("\n".join(out))
    print("wrote", DST, "worst pole radius %.5f" % maxcheck)


if __name__ == "__main__":
    main()
